# Generated by Django 3.0.6 on 2020-08-05 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='stock',
            new_name='Ticker',
        ),
    ]
